globalConfig:
  author: chuck
  open: false
  idType: NONE
  dateType: ONLY_DATE
  enableCache: false
  activeRecord: false
  baseResultMap: true
  baseColumnList: true
  swagger2: false
  fileOverride: true
dataSourceConfig:
  url: jdbc:mysql://39.97.124.2:3306/driving_school?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
  driverName: com.mysql.cj.jdbc.Driver
  username: driving_school
  password: aWBBLaTmwbsjSspF
packageConfig:
  parent: cn.structured.mybatisplus.generate.example
  moduleName:
  entity: entity
  service: service
  serviceImpl: service.impl
  mapper: dao
  xml: mapper
  controller: controller
  pathInfo:
    entity_path: .\src\main\java\cn\structured\mybatisplus\generate\example\entity
    service_path: .\src\main\java\cn\structured\mybatisplus\generate\example\service
    service_impl_path: .\src\main\java\cn\structured\mybatisplus\generate\example\service\impl
    mapper_path: .\src\main\java\cn\structured\mybatisplus\generate\example\dao
    xml_path: .\src\main\resources\mapper
    controller_path: .\src\main\java\cn\structured\mybatisplus\generate\example\controller
strategyConfig:
  naming: underline_to_camel
  columnNaming: underline_to_camel
  entityLombokModel: true
  superMapperClass: com.baomidou.mybatisplus.core.mapper.BaseMapper
  superServiceClass: com.baomidou.mybatisplus.extension.service.IService
  superServiceImplClass: com.baomidou.mybatisplus.extension.service.impl.ServiceImpl
  controllerMappingHyphenStyle: true
  restControllerStyle: true
  tablePrefix:
  include:
  - user_info
tableFill:
  is_deleted: INSERT
  create_time: INSERT
  update_time: INSERT_UPDATE

